[package]
name = "rsbadges"
version = "0.1.0"
authors = ["Brandon Minor <gallimatrix@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
css-color = "0.1"
getopts = "0.2"